### ISSUE TITLE
test 코드 작성

### ISSUE THREAD

**Issue by lehebk** [leeheebok/Jpashop#11]

**Comment by safecorners** [comment]
1. test > resources> `application.yaml`: 인메모리h2로 변경
2. `MemberServiceTest`: junit4에서 @Test 임포트
3.  메소드 변경 시 테스트코드도 변경하기: Optional을 반환하는 하는 메소드
4. 병합 충돌 해결하기
    - [git - conflict 처리법 ](https://velog.io/@devmin/git-conflict-solution-basic)
